---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shivamohan07/microservices-config-server
          #username: user
          #password: pass
          searchPaths: component*
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/Shivamohan07/microservices-config-server-perf
              searchPaths: component*